# We will use cops to detect bugs in an early stage
# Feel free to use .rubocop_todo.yml by --auto-gen-config
inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rubycw
  - rubocop-rake

AllCops:
  # drop support for < 2.7
  TargetRubyVersion: 2.7
  # accept new cops if any
  NewCops: enable

# ===

# alias is hard to see separately 
Style/Alias:
  EnforcedStyle: prefer_alias_method

# For consistency and portability
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
# Should not set for Style/TrailingCommaInArguments

# ===

# To let you know the possibility of refactoring ===
#
# avoid unused variable asignment
Rubycw/Rubycw:
  Exclude:
    - 'test/**/*'
Lint/UselessAssignment:
  Exclude:
    - 'test/**/*'

# Max: 120
Layout/LineLength:
  Max: 100
  Exclude:
    - 'test/**/*'

# <= 17 satisfactory
# 18..30 unsatisfactory
# > 30 dangerous
Metrics/AbcSize:
  Max: 19
  Exclude:
    - 'lib/red_amber/data_frame_output.rb' # Max: 78

# Max: 25
Metrics/BlockLength:
  Max: 25
  Exclude:
    - 'test/**/*'
    - '*.gemspec'

# Max: 100
Metrics/ClassLength:
  Max: 100
  Exclude:
    - 'test/**/*'

# Max: 7
Metrics/CyclomaticComplexity:
  Max: 10
  Exclude:
    - 'lib/red_amber/data_frame_output.rb' # Max: 11

# Max: 10
Metrics/MethodLength:
  Max: 18
  Exclude:
    - 'lib/red_amber/data_frame_output.rb' # Max: 35

# Max: 8
Metrics/PerceivedComplexity:
  Max: 9
  Exclude:
    - 'lib/red_amber/data_frame_output.rb' # Max: 12
